npm audit fix
dial-once/node-cache-manager-redis pull request #81
Opened 2018-07-02 14:40 UTC by RiccardiLd

2018-07-02 14:42 UTC, jkernech approved these changes

2018-07-02 15:21 UTC, mrister requested changes
this is a library/module package-lock.json should be removed and gitignored!

2018-07-03 13:09 UTC, jkernech approved these changes

2018-07-03 14:49 UTC, mrister approved these changes

2018-07-03 14:57 UTC, merged